# Generated by Django 5.1.4 on 2025-01-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='phone',
        ),
    ]
