# Generated by Django 5.1.4 on 2025-02-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='special_info',
            field=models.TextField(blank=True, help_text='Enter any special vehicle information', null=True),
        ),
    ]
