# Generated by Django 5.1.4 on 2025-02-04 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driverprofile_special_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the correct format: +0123456789.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
