# Generated by Django 5.1.4 on 2025-01-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('arrived_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('owner_passengers', models.PositiveIntegerField(default=1)),
                ('can_shared', models.BooleanField(default=False)),
                ('special_request', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type_request', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_ride', to='users.driverprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_ride', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RideShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.PositiveIntegerField(default=1)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_share', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_share', to='users.userprofile')),
            ],
            options={
                'unique_together': {('ride', 'user')},
            },
        ),
    ]
