# Generated by Django 5.1.4 on 2025-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        ('users', '0004_remove_userprofile_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rideshare',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rideshare',
            constraint=models.UniqueConstraint(fields=('ride', 'user'), name='unique_user_ride'),
        ),
    ]
